CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY SERIAL NOT NULL,
    username VARCHAR(32) NOT NULL,
    email VARCHAR(64) NOT NULL,
    password VARCHAR(256) NOT NULL,
    unique_id VARCHAR(36) NOT NULL,
)

CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY SERIAL,
    title TEXT NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT 0,
    source INTEGER FOREIGN KEY(users(id)) NOT NULL,
)